AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - lib/ruby_by_ruby/interpreter.rb

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Exclude:
    - lib/ruby_by_ruby/interpreter.rb